[users]
bob = "$2b$12$orUAGMCeb/cpxu54jZu3/u13XJ78gJMkouC38s0heSo.00yEvFa7e"


[connections.mysql]
dialect = "mysql"
host = "localhost"
port = 3306
database = "STOCKMANAGER"
username = "mysql"
password = "mysql"

[mongodbAPI]
uri = "mongodb+srv://stockmanager:mongo@ktscluster.fnabh5x.mongodb.net/?retryWrites=true&w=majority&appName=KTSCluster"
